import { centred, FOLLOWED, GROUND_Y, note, type Beat } from '../../../../paper'
import {
  barked,
  camera,
  ghost,
  ground,
  hot,
  line,
  narrator,
  row,
  rowA,
  rowB,
  type Patch,
} from './scene'

/**
 * Section 04 — The word looks around.
 *
 * The viewer arrives with a real problem: the starting embedding is fixed, but
 * words clearly change meaning with context. We solve that problem on screen
 * before using the name "attention". The visual remains an intuition for the
 * job; GLM's real attention stack is hybrid and more complicated than these
 * lines imply.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'starts-out-identical',
    title: 'The three identical rows collapse into one',
    relation: 'want',
    secs: 8,
    vo: 'That is the problem. The starting embedding for the same token is fixed.',
    commands: [
      ground.at(GROUND_Y),
      row.show({ x: 50, y: 44 }, 0.7),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'think', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'never-on-its-own',
    title: 'We back off; every token’s row is there, in a line',
    relation: 'so',
    secs: 8,
    vo: 'But a token is not alone. It sits inside a sequence, next to other tokens.',
    commands: [
      row.off(),
      camera.to({ x: 50, y: 50 }, 0.86),
      line.show({ x: 50, y: 48 }, 1),
      narrator.set({ pose: 'point' }),
    ],
  },
  {
    n: 3,
    id: 'every-token-looks',
    title: 'Our row lifts slightly out of the line',
    relation: 'so',
    secs: 7,
    vo: 'So the model lets each position update itself using the context around it.',
    commands: [line.raise(FOLLOWED)],
  },
  {
    n: 4,
    id: 'how-much-do-you-matter',
    title: 'Lines shoot from our row to every other row',
    relation: 'so',
    secs: 10,
    vo: 'For the token we are following, imagine it asking: which other positions matter to me right now?',
    commands: [line.ask()],
    lateOverlays: {
      at: 3000,
      overlays: [centred('which positions\nmatter right now?', 50, 12, { size: 'md', tone: 'relate', rotate: -2 })],
    },
  },
  {
    n: 5,
    id: 'some-matter-a-lot',
    title: 'The lines thicken and thin',
    relation: 'so',
    secs: 7,
    vo: 'Some connections get more weight. Others barely contribute.',
    commands: [line.weigh()],
    overlays: [note('thicker = more weight', 78, 20, { tone: 'relate', rotate: 3, sticky: true })],
  },
  {
    n: 6,
    id: 'only-backwards',
    title: 'The lines running forward fade out and go',
    relation: 'wall',
    secs: 12,
    vo: 'And for left-to-right generation, a position can only use itself and positions before it. Anything to the right is masked out.',
    commands: [line.mask()],
    clearSticky: true,
    overlays: [note('this position + earlier ones', 20, 20, { tone: 'relate', rotate: -3 })],
  },
  {
    n: 7,
    id: 'mixes-it-in',
    title: 'Material travels along the surviving lines into our row',
    relation: 'so',
    secs: 9,
    vo: 'Then information from the allowed positions is mixed in, weighted by those connections.',
    commands: [line.pull()],
  },
  {
    n: 8,
    id: 'and-its-row-changes',
    title: 'Our row’s values visibly change where the flow landed',
    relation: 'and-yet',
    secs: 7,
    vo: 'And the row changes. Same token ID. New numbers that now carry context.',
    commands: [line.change(FOLLOWED)],
    overlays: [note('same token ID.\nnew contextual row.', 20, 76, { tone: 'measure', rotate: -2 })],
  },
  {
    n: 9,
    id: 'all-of-them-at-once',
    title: 'Every other row does the same thing at once, then settles',
    relation: 'so',
    secs: 10,
    vo: 'And every position does this in parallel, using only the context it is allowed to see.',
    commands: [line.changeAll(), line.raise(-1), narrator.set({ pose: 'count' })],
    lateOverlays: {
      at: 3000,
      overlays: [note('all positions\nin parallel', 20, 20, { size: 'md', tone: 'relate', rotate: -3 })],
    },
  },
  {
    n: 10,
    id: 'two-sentences',
    title: 'The sentence slides left; a second assembles beside it',
    relation: 'so',
    secs: 7,
    vo: 'Now compare two simple cases: "the dog barked" and "a hot dog".',
    commands: [
      line.off(),
      barked.show({ x: 26, y: 32 }, 0.5),
      hot.show({ x: 74, y: 32 }, 0.5),
      narrator.set({ pose: 'point' }),
    ],
  },
  {
    n: 11,
    id: 'how-different',
    title: 'Both `dog` rows lift out and align, still covered; nothing moves',
    relation: 'and-yet',
    secs: 12,
    vo: 'Same starting "dog" embedding in both. Do you expect the contextual rows to still look the same?',
    commands: [
      rowA.show({ x: 26, y: 58 }, 0.42, { covered: true }),
      rowB.show({ x: 74, y: 58 }, 0.42, { covered: true }),
      narrator.set({ pose: 'wonder' }),
    ],
    lateOverlays: {
      at: 3400,
      overlays: [centred('same after context?', 50, 88, { size: 'lg', rotate: -2, sticky: true })],
    },
  },
  {
    n: 12,
    id: 'nothing-like-each-other',
    title: 'The covers come off; the two rows are obviously unalike',
    relation: 'wall',
    secs: 6,
    vo: 'No. They can end up very different.',
    commands: [rowA.uncover(), rowB.uncover(), narrator.set({ pose: 'push' })],
    clearSticky: true,
  },
  {
    n: 13,
    id: 'same-row-both-times',
    title: 'The row they started from ghosts in behind both, identical',
    relation: 'so',
    secs: 7,
    vo: 'Same starting row. Different context.',
    commands: [ghost.show({ x: 50, y: 78 }, 0.42), narrator.set({ pose: 'aha' })],
    overlays: [centred('both started here', 50, 90, { rotate: -2 })],
  },
  {
    n: 14,
    id: 'the-word-in-this-sentence',
    title: 'The ghost fades; the two rows hold apart',
    relation: 'therefore',
    secs: 11,
    vo: 'That is the key: after this step, the numbers represent this token in this context, not just the token by itself.',
    commands: [ghost.off(), narrator.set({ pose: 'nod' })],
  },
  {
    n: 15,
    id: 'thats-attention',
    title: 'A handwritten label lands between the two rows',
    relation: 'so',
    secs: 11,
    vo: 'This is the intuition behind attention: a token updates its representation using the context around it.',
    commands: [narrator.set({ pose: 'nod' })],
    lateOverlays: {
      at: 3000,
      overlays: [centred('attention', 50, 44, { size: 'lg', tone: 'relate', rotate: -2, sticky: true })],
    },
  },
  {
    n: 16,
    id: 'could-not-have-known',
    title: 'The two rows hold apart; everything else recedes',
    relation: 'and-yet',
    secs: 13,
    vo: 'And now we have something new: a context-dependent row that did not exist before this sequence was processed. What does the model do with it?',
    commands: [narrator.set({ pose: 'think' })],
    clearSticky: true,
    lateOverlays: {
      at: 2600,
      overlays: [centred('a row that depends on\nthis context', 50, 84, { size: 'md', tone: 'cost', rotate: 1 })],
    },
  },
]
