import { centred, GROUND_Y, note, type Beat } from '../../../../paper'
import {
  SLOTS,
  cache,
  count,
  ground,
  hangover,
  machine,
  narrator,
  path,
  slider,
  store,
  tower,
  wall,
  type Patch,
} from './scene'

/**
 * Section 12 — How people actually run these with less fast memory.
 *
 * This is the correction to §11's deliberately naive plan. Expert offloading
 * and caching are real. What we do not have is published locality data for
 * GLM's 288-routed-expert, top-8 regime that lets us name an optimal cache size
 * or hit rate. The section therefore teaches the trade, not a fake verdict.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'people-do-run-these',
    title: 'The bars clear; a small machine slides in and runs, steadily',
    relation: 'wall',
    secs: 12,
    vo: 'And this is the important correction: people really do run large mixture-of-experts models with expert offloading and much less fast memory.',
    commands: [
      ground.at(GROUND_Y),
      machine.show({ x: 72, y: 54 }, 1),
      machine.say(['bounced', 'off', 'the']),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'confide', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'what-are-they-doing',
    title: 'The machine keeps running while §11’s numbers hang over it',
    relation: 'and-yet',
    secs: 8,
    vo: 'So how do they avoid the eight-and-a-half-gigabyte fetch we just drew?',
    commands: [hangover.show({ x: 72, y: 14 }, 1)],
  },
  {
    n: 3,
    id: 'caching',
    title: 'A box appears in the path between the drive and the machine',
    relation: 'so',
    secs: 6,
    vo: 'They cache experts.',
    commands: [
      store.show({ x: 12, y: 50 }, 0.52),
      path.fetch(4),
      cache.show({ x: 43, y: 50 }, 1, { filled: 0 }),
    ],
    overlays: [note('cache', 43, 30, { size: 'md', rotate: -2 })],
  },
  {
    n: 4,
    id: 'experts-repeat',
    title: 'Two words run through; a couple of the same blocks used both times',
    relation: 'so',
    secs: 10,
    vo: 'If an expert gets used again, leave it in fast memory instead of throwing it out immediately.',
    commands: [path.fetch(8)],
    stages: [{ at: 2200, commands: [cache.fill(3)] }],
  },
  {
    n: 5,
    id: 'quite-often-the-same',
    title: 'The repeating blocks stay in the box instead of returning',
    relation: 'so',
    secs: 9,
    vo: 'Then a later token can hit the cache instead of going back to storage for that expert.',
    commands: [cache.fill(5), cache.hit(2)],
    overlays: [note('reuse → cache hit', 43, 28, { tone: 'word', rotate: 3 })],
  },
  {
    n: 6,
    id: 'only-fetch-the-misses',
    title: 'The next word’s fetches split: most from the box, a few from the drive',
    relation: 'so',
    secs: 10,
    vo: 'You fetch only the experts that are missing. Hits take the short path; misses take the long one.',
    commands: [cache.fill(7), cache.hit(5), path.fetch(3)],
    overlays: [note('short hop = hit\nlong hop = miss', 22, 30, { tone: 'measure', rotate: -3 })],
  },
  {
    n: 7,
    id: 'and-it-works',
    title: 'The machine speeds up; a model tag appears on the box',
    relation: 'hope',
    secs: 13,
    vo: 'And this is real. On smaller-expert-count mixture-of-experts models, published systems show that expert caching and offloading can work well.',
    commands: [
      cache.cite('locality measured on smaller-expert-count MoE models'),
      machine.say(['bounced', 'off', 'the', 'wall']),
      narrator.set({ pose: 'cheer' }),
    ],
  },
  {
    n: 8,
    id: 'how-much-do-you-keep',
    title: 'A slider rises out of the floor under the box',
    relation: 'so',
    secs: 9,
    vo: 'Now the real question becomes: how much fast memory do you give the cache?',
    commands: [slider.show({ x: 17, y: 78 }, 1)],
  },
  {
    n: 9,
    id: 'wheres-the-good-setting',
    title: 'The slider holds untouched at neither end; nothing moves',
    relation: 'and-yet',
    secs: 11,
    vo: 'You already know the trade: more cache is faster but bigger; less cache is smaller but slower. Where would you put the slider?',
    commands: [slider.ask('where would you put it?'), narrator.set({ pose: 'wonder' })],
  },
  {
    n: 10,
    id: 'keep-more-and-its-big',
    title: 'Dragged up: the box swells, the machine races, its frame grows huge',
    relation: 'and-yet',
    secs: 10,
    vo: 'Push it high and misses drop — but you are back to needing lots of fast memory.',
    commands: [slider.drive(0.95), path.fetch(1), cache.fill(24), cache.hit(20)],
    overlays: [note('fast · bigger cache', 72, 88, { tone: 'cost', rotate: 2 })],
  },
  {
    n: 11,
    id: 'keep-less-and-it-crawls',
    title: 'Dragged down: the box shrinks, long hops multiply, it crawls',
    relation: 'wall',
    secs: 10,
    vo: 'Push it low and the machine gets small — but misses pile up and transfers slow you down.',
    commands: [slider.drive(0.06), cache.fill(2), cache.hit(0), path.pileUp()],
    overlays: [note('small · more misses', 72, 88, { tone: 'cost', rotate: -2 })],
  },
  {
    n: 12,
    id: 'remember-what-were-choosing-from',
    title: 'The 288 wall and the 42 floors ghost in behind the box, dwarfing it',
    relation: 'and-yet',
    secs: 10,
    vo: 'GLM makes that tuning problem large: two hundred and eighty-eight routed experts on each of forty-two sparse layers.',
    commands: [
      wall.show({ x: 43, y: 36 }, 0.62),
      tower.show({ x: 66, y: 42 }, 0.5),
      path.fetch(0),
    ],
  },
  {
    n: 13,
    id: 'twelve-thousand-and-ninety-six',
    title: 'A count assembles from them and lands on the box',
    relation: 'wall',
    secs: 8,
    vo: 'That is twelve thousand and ninety-six routed expert slots across the sparse layers.',
    commands: [count.run(SLOTS, 'routed expert slots across sparse layers')],
    overlays: [note('288 × 42', 28, 17, { size: 'md', tone: 'measure', rotate: -2, sticky: true })],
  },
  {
    n: 14,
    id: 'no-setting-where-its-both',
    title: 'The slider is dragged across its whole range; neither end shows both',
    relation: 'therefore',
    secs: 17,
    vo: 'And here is the line we cannot cross: we do not have published locality measurements for GLM’s two-hundred-and-eighty-eight-expert, top-eight routing that tell us the ideal cache point.',
    commands: [count.hold(), wall.off(), tower.off(), slider.drive(0.92)],
    clearSticky: true,
    stages: [
      { at: 2200, commands: [slider.drive(0.08), cache.fill(2), cache.hit(0)] },
      { at: 4400, commands: [slider.drive(0.5), cache.fill(9), cache.hit(4)] },
    ],
  },
  {
    n: 15,
    id: 'nobody-knows-where',
    title: 'A question mark settles over the middle of the range, where a position would go',
    relation: 'wall',
    secs: 13,
    vo: 'So I cannot honestly give you a magic cache size or hit rate. And “five percent active” does not tell you either one.',
    commands: [slider.drive(0.5), narrator.set({ pose: 'flat' })],
    lateOverlays: {
      at: 3200,
      overlays: [centred('no measured GLM cache optimum', 17, 92, { size: 'md', tone: 'cost', rotate: -2 })],
    },
  },
  {
    n: 16,
    id: 'a-price-not-a-wall',
    title: 'The slider settles mid-range; the machine runs, slowly, and keeps running',
    relation: 'and-yet',
    secs: 12,
    vo: 'But less fast memory is possible. You pay for it with more transfers and less speed. It is a trade, not a hard wall.',
    commands: [
      slider.release(),
      path.fetch(5),
      machine.say(['bounced', 'off', 'the', 'wall', 'and']),
      narrator.set({ pose: 'nod' }),
    ],
    lateOverlays: {
      at: 3000,
      overlays: [centred('a trade, not a hard wall', 50, 92, { size: 'md', rotate: -1 })],
    },
  },
]
