import { centred, GROUND_Y, note, type Beat } from '../../../../paper'
import { CHOSEN, blend, ground, hospital, narrator, room, row, type Patch } from './scene'

/**
 * Section 06 — The experts do the work.
 *
 * The fair prediction here is whether one expert wins. The viewer has enough
 * information to make that guess, and the answer matters: all eight outputs
 * contribute, weighted by the router scores.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'what-do-they-do',
    title: 'The eight lift forward; the 280 recede',
    relation: 'want',
    secs: 8,
    vo: 'Okay. The router picked eight experts. What do those eight actually do?',
    commands: [
      ground.at(GROUND_Y),
      hospital.show({ x: 50, y: 12 }, 0.3, { lit: CHOSEN }),
      hospital.recede(),
      blend.show({ x: 50, y: 52 }, 0.94),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'wonder', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'each-takes-the-row',
    title: 'The row copies eight times, one copy into each',
    relation: 'so',
    secs: 6,
    vo: 'The same input row is sent to all eight.',
    commands: [blend.copy(), narrator.set({ pose: 'point' })],
  },
  {
    n: 3,
    id: 'eight-different-answers',
    title: 'Eight visibly different rows emerge on the far side',
    relation: 'so',
    secs: 8,
    vo: 'Each expert transforms it differently, so eight different output rows come back.',
    commands: [blend.out()],
    overlays: [note('same row in, eight\ndifferent rows out', 12, 22, { tone: 'measure', rotate: -3 })],
  },
  {
    n: 4,
    id: 'which-one-wins',
    title: 'The eight outputs hold side by side; nothing moves',
    relation: 'and-yet',
    secs: 8,
    vo: 'Now make a guess: does the model choose one winner, or use all eight?',
    commands: [narrator.set({ pose: 'wonder' })],
    lateOverlays: {
      at: 2400,
      overlays: [centred('one winner — or all eight?', 50, 88, { size: 'lg', rotate: -2, sticky: true })],
    },
  },
  {
    n: 5,
    id: 'none-of-them',
    title: 'All eight stay; none dims, none leaves',
    relation: 'so',
    secs: 6,
    vo: 'All eight. None wins outright.',
    commands: [narrator.set({ pose: 'flat' })],
    clearSticky: true,
    overlays: [note('all eight contribute', 12, 80, { size: 'md', tone: 'word', rotate: -3 })],
  },
  {
    n: 6,
    id: 'not-an-equal-say',
    title: 'Each output takes the size of its expert’s score',
    relation: 'and-yet',
    secs: 10,
    vo: 'But not equally. The router scores become weights: a higher score means a bigger contribution.',
    commands: [blend.weigh()],
    lateOverlays: {
      at: 2800,
      overlays: [note('higher score =\nbigger contribution', 88, 22, { tone: 'measure', rotate: 3, sticky: true })],
    },
  },
  {
    n: 7,
    id: 'blended-in-proportion',
    title: 'The eight converge and merge, larger ones dominating',
    relation: 'so',
    secs: 6,
    vo: 'Those eight outputs are blended into one row.',
    commands: [blend.merge()],
  },
  {
    n: 8,
    id: 'plus-the-always-on',
    title: 'The dashed shared expert’s output joins the merge',
    relation: 'so',
    secs: 7,
    vo: 'And the shared expert’s output joins the blend too.',
    commands: [blend.plusOne()],
  },
  {
    n: 9,
    id: 'a-single-row',
    title: 'One row settles, the same length as the one that went in',
    relation: 'therefore',
    secs: 9,
    vo: 'So we are back to one row. Same length as before, but with different numbers.',
    commands: [blend.done()],
    clearSticky: true,
  },
  {
    n: 10,
    id: 'before-and-after',
    title: 'The row that arrived ghosts in beside it',
    relation: 'and-yet',
    secs: 7,
    vo: 'That is one sparse feed-forward step: before, and after.',
    commands: [blend.compare()],
  },
  {
    n: 11,
    id: 'same-shape-it-was',
    title: 'The ghost fades; everything else clears; the row is alone',
    relation: 'so',
    secs: 13,
    vo: 'The important part is the shape stayed the same: four thousand and ninety-six numbers went in, and four thousand and ninety-six came out. So the next layer can take over.',
    commands: [
      blend.off(),
      hospital.off(),
      row.show({ x: 50, y: 50 }, 0.72, { label: 'one step, done' }),
      narrator.set({ pose: 'nod' }),
    ],
  },
  {
    n: 12,
    id: 'the-room-gets-edges',
    title: 'The room’s walls, floor and ceiling draw themselves in around the row',
    relation: 'therefore',
    secs: 11,
    vo: 'So one layer can be pictured as a simple cycle: use context, choose experts, transform the row.',
    commands: [room.draw(), ground.at(GROUND_Y), narrator.off()],
  },
  {
    n: 13,
    id: 'how-many-steps',
    title: 'The room shrinks in frame; edges above and below hint at more of them',
    relation: 'and-yet',
    secs: 9,
    vo: 'And now the obvious question: how many layers does this token have to go through?',
    commands: [room.hintAtMore(0.82)],
    lateOverlays: {
      at: 2600,
      overlays: [centred('how many layers?', 50, 90, { size: 'md', rotate: -2 })],
    },
  },
]
