import { centred, GROUND_Y, note, PROMPT, REPLY, TOKENS, type Beat } from '../../../../paper'
import { aside, ground, line, loop, narrator, out, tower, visitsAfter, type Patch } from './scene'

/**
 * Section 10 — And then it does it again.
 *
 * This section makes the prefill/decode distinction explicit. The earlier
 * tokens do not all climb the stack again; the model keeps the state it needs
 * from them and pushes only the new token through the layers.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'one-word-out-of-a-machine',
    title: 'The tower and the single word card hold, apart',
    relation: 'want',
    secs: 8,
    vo: 'That explains one output token. But a reply needs another one after that.',
    commands: [
      ground.at(GROUND_Y),
      tower.show({ x: 28, y: 48 }, 0.82),
      out.show({ x: 62, y: 22 }, 0.62, { label: REPLY[0] }),
      line.show({ x: 28, y: 93 }, 0.3),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'wonder', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'does-it-get-a-shortcut',
    title: 'The card hovers near the base; nothing else moves',
    relation: 'and-yet',
    secs: 10,
    vo: 'So what happens now? Does the whole prompt climb all forty-five layers again?',
    commands: [out.moveTo({ x: 30, y: 88 }, 0.3)],
  },
  {
    n: 3,
    id: 'no-shortcut',
    title: 'The card drops to the base and sits on floor one',
    relation: 'so',
    secs: 7,
    vo: 'No. The earlier tokens do not climb again.',
    commands: [out.moveTo({ x: 31, y: 78 }, 0.3), tower.set({ floor: 1 })],
  },
  {
    n: 4,
    id: 'joins-the-end',
    title: 'The sentence is now one token longer; a ninth marker appears',
    relation: 'so',
    secs: 7,
    vo: 'The new token is appended to the sequence.',
    commands: [out.off(), line.grow([...PROMPT, REPLY[0]]), tower.set({ markers: TOKENS + 1, floor: 1, kept: 0 })],
    lateOverlays: {
      at: 2400,
      overlays: [note('9 tokens now', 28, 86, { tone: 'measure', rotate: -3 })],
    },
  },
  {
    n: 5,
    id: 'what-is-kept',
    title: 'The eight earlier markers hold in place; none of them move',
    relation: 'and-yet',
    secs: 12,
    vo: 'The model keeps the state it needs from those earlier positions, so their work does not have to be repeated.',
    commands: [tower.set({ kept: TOKENS }), loop.show({ x: 74, y: 50 }, 0.9), loop.start()],
  },
  {
    n: 6,
    id: 'just-the-new-word',
    title: 'Only the ninth marker enters the base and climbs alone',
    relation: 'so',
    secs: 10,
    vo: 'Only the new token moves through the forty-five layers, reading the kept state as it goes.',
    commands: [aside.show({ x: 15, y: 18 }, 1)],
    stages: [
      { at: 1200, commands: [tower.climbTo(18)] },
      { at: 3000, commands: [tower.climbTo(33)] },
    ],
  },
  {
    n: 7,
    id: 'three-thirty-six-for-this-word',
    title: '42 of the 45 floors light as it passes; a counter runs with it',
    relation: 'so',
    secs: 12,
    vo: 'On the forty-two sparse layers it still routes to eight experts: another three hundred and thirty-six routed expert visits for this new token.',
    commands: [loop.show({ x: 74, y: 50 }, 0.9), loop.start(), loop.faster(0.3)],
    stages: [{ at: 2600, commands: [tower.climbTo(45)] }],
    lateOverlays: {
      at: 5000,
      overlays: [note('336 — for this new token', 58, 18, { size: 'md', tone: 'measure', rotate: -2 })],
    },
  },
  {
    n: 8,
    id: 'another-word-comes-out',
    title: 'Another card drops out at the top',
    relation: 'so',
    secs: 4,
    vo: 'Then another token comes out.',
    commands: [loop.say(REPLY.slice(0, 2)), loop.count(visitsAfter(2))],
  },
  {
    n: 9,
    id: 'then-again-and-again',
    title: 'The cycle repeats, accelerating each time',
    relation: 'so',
    secs: 9,
    vo: 'Append it. Run the new token. Pick another. Repeat.',
    commands: [loop.faster(0.62), aside.off()],
    stages: [
      { at: 1200, commands: [loop.say(REPLY.slice(0, 4)), loop.count(visitsAfter(4)), tower.climbTo(20)] },
      { at: 3000, commands: [loop.faster(0.9), loop.say(REPLY), loop.count(visitsAfter(6)), tower.climbTo(41)] },
    ],
  },
  {
    n: 10,
    id: 'while-you-sit-there',
    title: 'The produced words accumulate as a line of text beside the tower',
    relation: 'so',
    secs: 9,
    vo: 'That loop is what you are watching when the answer appears one piece at a time.',
    commands: [narrator.set({ pose: 'lean' })],
    overlays: [note('this is the typing loop', 74, 12, { rotate: -2 })],
  },
  {
    n: 11,
    id: 'full-stack-fresh-choices',
    title: 'A counter beside each produced word ticks 336 per token',
    relation: 'so',
    secs: 13,
    vo: 'For our eight-token prompt, the prompt pass cost two thousand, six hundred and eighty-eight routed expert visits. After that, every generated token adds another three hundred and thirty-six.',
    commands: [],
    overlays: [centred('2,688 once\n+336 per generated token', 52, 34, { tone: 'measure', rotate: 3, sticky: true })],
  },
  {
    n: 12,
    id: 'not-known-in-advance',
    title: 'The running total climbs and does not stop',
    relation: 'and-yet',
    secs: 10,
    vo: 'And each new token can take a different expert path, because the representations it creates are new.',
    commands: [loop.faster(1), narrator.set({ pose: 'push' })],
  },
  {
    n: 13,
    id: 'it-never-stops-choosing',
    title: 'Everything halts at once',
    relation: 'wall',
    secs: 7,
    vo: 'So the model keeps routing, token after token.',
    commands: [loop.halt(), narrator.set({ pose: 'think' })],
    clearSticky: true,
  },
  {
    n: 14,
    id: 'the-question-we-started-with',
    title: 'The tower and the finished reply hold together in frame',
    relation: 'and-yet',
    secs: 10,
    vo: 'Now we finally have enough to answer the opening question: why not keep only the part that is active?',
    commands: [tower.set({ markers: 0, kept: 0 })],
  },
]
