import { arrow, brace, centred, GROUND_Y, note, type Beat } from '../../../../paper'
import { block, block2, chat, ground, rigA, rigB, type Patch } from './scene'

/**
 * Section 01 — The five-percent problem.
 *
 * NARRATION LOCKED. The spoken script was approved before this board was built.
 * Beats, timing and visuals adapt to that narration; the narration does not get
 * paraphrased to fit the implementation. See `skills/STORY_STRUCTURE.md`.
 *
 * No tower, 45 floors, 288 experts, 336 visits, router, or MoE language here.
 * Those facts matter later, after the viewer knows what they count.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'the-advertised-number',
    title: 'GLM arrives; 320B total and 18B active become the only two numbers',
    relation: 'want',
    secs: 11,
    vo: 'You’ve probably seen AI models advertised like this: 320 billion parameters. Only 18 billion active. And that sounds incredible.',
    commands: [
      ground.at(GROUND_Y),
      block.scatter({ x: 50, y: 47 }, 0.78),
      block.pack(),
      block.light('a'),
    ],
    overlays: [
      centred('GLM-5.3-Flash', 50, 14, { size: 'sm', sticky: true }),
      note('320B total', 29, 72, { tone: 'measure', sticky: true }),
      note('18B active', 61, 28, { tone: 'claim', sticky: true }),
    ],
  },
  {
    n: 2,
    id: 'surely-you-only-need-that-part',
    title: 'The active region lifts out as the obvious interpretation',
    relation: 'therefore',
    secs: 10,
    vo: 'Because if only a small part of the model is being used at a time… then surely you only need that small part.',
    commands: [block.lift()],
    overlays: [note('keep this part?', 65, 20, { size: 'md', rotate: -3 })],
  },
  {
    n: 3,
    id: 'thats-what-i-assumed',
    title: 'The lifted patch settles back; the assumption is allowed to feel reasonable',
    relation: 'want',
    secs: 8,
    vo: 'Right? Honestly, that’s what I assumed too. So let me show you something weird.',
    commands: [block.drop()],
    overlays: [centred('sounds reasonable', 50, 83, { size: 'sm', rotate: 2 })],
  },
  {
    n: 4,
    id: 'four-percent-six-percent',
    title: 'A second model arrives; the two active shares are shown separately',
    relation: 'so',
    secs: 12,
    vo: 'Here are two models. This one uses about 4% of its parameters when generating a token. This one uses about 6%.',
    commands: [
      block.moveTo({ x: 70, y: 42 }, 0.58),
      block2.arrive({ x: 30, y: 42 }, 0.58),
      block2.light('b'),
    ],
    clearSticky: true,
    overlays: [
      centred('gpt-oss-120b', 30, 15, { size: 'sm', sticky: true }),
      centred('GLM-5.3-Flash', 70, 15, { size: 'sm', sticky: true }),
      centred('≈4% active', 30, 61, { size: 'sm', tone: 'claim', sticky: true }),
      centred('≈6% active', 70, 61, { size: 'sm', tone: 'claim', sticky: true }),
    ],
  },
  {
    n: 5,
    id: 'expect-a-small-difference',
    title: 'The models hold while the viewer predicts the hardware gap',
    relation: 'want',
    secs: 11,
    vo: 'Pretty close. So if I asked you which one needs more hardware… you’d probably expect the difference to be pretty small.',
    commands: [],
    overlays: [
      note('SMALL DIFFERENCE?', 37, 78, { size: 'md', backed: true, rotate: -1 }),
    ],
  },
  {
    n: 6,
    id: 'it-isnt-one-accelerator',
    title: 'One 80 GB accelerator lands under the left model',
    relation: 'and-yet',
    secs: 8,
    vo: 'It isn’t. This one can fit on a single 80-gigabyte accelerator.',
    commands: [rigA.show(1, { x: 30, y: 74 }, 0.82)],
    overlays: [note('1 × 80 GB', 23, 86, { tone: 'measure', sticky: true })],
  },
  {
    n: 7,
    id: 'this-one-takes-eight',
    title: 'GLM counts up to eight accelerators, one visible step at a time',
    relation: 'and-yet',
    secs: 8,
    vo: 'Keeping this one fully resident at the precision it ships in takes eight.',
    commands: [rigB.show(1, { x: 70, y: 74 }, 0.82)],
    stages: [
      { at: 700, commands: [rigB.show(2)] },
      { at: 1500, commands: [rigB.show(4)] },
      { at: 2500, commands: [rigB.show(8)] },
    ],
    overlays: [
      note('8 × 80 GB', 64, 86, { tone: 'cost', sticky: true }),
      centred('native shipped precision · weights resident', 70, 93, { size: 'sm' }),
    ],
  },
  {
    n: 8,
    id: 'same-promise-different-machine',
    title: 'The 4%/6% comparison holds above one accelerator versus eight',
    relation: 'wall',
    secs: 10,
    vo: 'Same basic promise: most of the model is inactive. Completely different machine.',
    commands: [],
    overlays: [brace('almost the same active share', 18, 63, 64, { tone: 'claim', side: 'top' })],
  },
  {
    n: 9,
    id: 'a-stranger-question',
    title: 'The comparison leaves; the same GLM block returns to centre',
    relation: 'therefore',
    secs: 5,
    vo: 'And that raises a much stranger question.',
    commands: [
      block2.off(),
      rigA.off(),
      rigB.off(),
      block.moveTo({ x: 50, y: 45 }, 0.84),
    ],
    clearSticky: true,
    overlays: [centred('GLM-5.3-Flash', 50, 12, { size: 'sm', sticky: true })],
  },
  {
    n: 10,
    id: 'which-eighteen-billion',
    title: 'A dashed alternative patch appears while the real active patch stays lit',
    relation: 'want',
    secs: 8,
    vo: 'When they say 18 billion parameters are active… which 18 billion?',
    commands: [block.ghost('b')],
    overlays: [
      note('18B active', 63, 27, { tone: 'claim' }),
      note('?', 74, 39, { size: 'lg', rotate: 8 }),
    ],
  },
  {
    n: 11,
    id: 'are-they-sitting-together',
    title: 'The active marks stay visibly scattered; a question brackets the region',
    relation: 'want',
    secs: 6,
    vo: 'Are they sitting together somewhere inside the model?',
    commands: [block.ghost(undefined)],
    overlays: [centred('one fixed place?', 50, 82, { size: 'md', rotate: -2 })],
  },
  {
    n: 12,
    id: 'same-eighteen-every-time',
    title: 'The hypothetical active outline moves to different places',
    relation: 'want',
    secs: 6,
    vo: 'Are they the same 18 billion every time?',
    commands: [block.ghost('b')],
    stages: [
      { at: 1600, commands: [block.ghost('c')] },
      { at: 3300, commands: [block.ghost('b')] },
    ],
  },
  {
    n: 13,
    id: 'does-it-know-before-you-ask',
    title: 'The alternatives clear; the intact model holds before any prompt exists',
    relation: 'want',
    secs: 9,
    vo: 'Does the model already know which ones it’s going to need before you ask it anything?',
    commands: [block.ghost(undefined)],
    overlays: [centred('known before the prompt?', 50, 82, { size: 'md', rotate: 2 })],
  },
  {
    n: 14,
    id: 'keep-the-useful-part',
    title: 'The active patch lifts out again as the tempting plan becomes concrete',
    relation: 'therefore',
    secs: 12,
    vo: 'Because if the answer to those questions were simple… you really could just keep the useful part and forget the rest.',
    commands: [block.lift()],
    overlays: [centred('KEEP READY?', 68, 19, { size: 'md', rotate: -2 })],
  },
  {
    n: 15,
    id: 'follow-one-piece-instead',
    title: 'The patch returns; GLM moves right and the familiar chat enters',
    relation: 'and-yet',
    secs: 13,
    vo: 'But that’s not what happens. And the easiest way to understand why is not with a giant architecture diagram. We’re going to follow one tiny piece of text through the entire model.',
    commands: [
      block.drop(),
      block.moveTo({ x: 76, y: 46 }, 0.48),
      chat.open({ x: 33, y: 46 }, 0.82, 'GLM-5.3-Flash'),
    ],
    clearSticky: true,
  },
  {
    n: 16,
    id: 'type-the-running-prompt',
    title: 'The one real prompt types into the chat; no token exists yet',
    relation: 'so',
    secs: 10,
    vo: 'Just one. Let’s type: “The dog dropped the ball, and it…”',
    commands: [chat.type('The dog dropped the ball, and it')],
    overlays: [centred('exact prompt used for the tokenizer', 33, 69, { size: 'sm', tone: 'word' })],
  },
  {
    n: 17,
    id: 'follow-it',
    title: 'Typing stops; an arrow identifies the final “it” without detaching it from the sentence',
    relation: 'therefore',
    secs: 14,
    vo: 'And we’re going to follow “it.” By the time that little piece reaches the other side, the whole 320 billion versus 18 billion thing should finally make sense.',
    commands: [chat.sent()],
    overlays: [
      note('follow “it”', 34, 70, { size: 'md', tone: 'word', rotate: -3, sticky: true }),
      arrow({ x: 720, y: 770 }, { x: 790, y: 615 }, { tone: 'word' }),
    ],
  },
  {
    n: 18,
    id: 'it-doesnt-start-with-words',
    title: 'Send is committed; a causal path begins toward GLM and stops halfway',
    relation: 'wall',
    secs: 13,
    vo: 'So first: when you type this sentence into the model… what does the model actually receive? Because it doesn’t start with words.',
    commands: [],
    clearSticky: true,
    overlays: [
      arrow(
        { x: 760, y: 520 },
        { x: 1090, y: 520 },
        { tone: 'word', dashed: true, label: '?' },
      ),
    ],
  },
]
