import { GROUND_Y, note, type Beat } from '../../../../paper'
import {
  CHOSEN,
  OTHER,
  arcs,
  camera,
  count,
  desk,
  ground,
  hospital,
  narrator,
  open,
  plates,
  row,
  row2,
  shared,
  type Patch,
} from './scene'

/**
 * Section 05 — The router picks the eight.
 *
 * The section starts from the contextual row §4 just produced. Facts the viewer
 * cannot infer — 288 routed experts, top 8, one shared expert — are stated
 * directly. The reasoning question is different: what information can the
 * router possibly use to choose?
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'something-has-to-read-it',
    title: 'The changed row travels right and rests at the unlabelled desk',
    relation: 'want',
    secs: 9,
    vo: 'That context-dependent row arrives here. Now the model has to decide what should process it next.',
    commands: [
      ground.at(GROUND_Y),
      row.show({ x: 22, y: 44 }, 0.44, { label: 'the row, as attention left it' }),
      camera.to({ x: 54, y: 50 }, 1),
      desk.show({ x: 62, y: 62 }, 0.8),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'point', flip: true }),
    ],
    stages: [{ at: 1800, commands: [row.moveTo({ x: 40, y: 44 }, 0.44)] }],
  },
  {
    n: 2,
    id: 'this-is-the-router',
    title: 'A small plaque lands on the desk',
    relation: 'so',
    secs: 9,
    vo: 'This little dispatcher is the router. Its job is to choose which experts should handle this row.',
    commands: [desk.name(), desk.ring(), narrator.set({ pose: 'offer' })],
  },
  {
    n: 3,
    id: 'two-eighty-eight-in-front',
    title: 'We back off and the 288 fill the frame beyond the desk',
    relation: 'so',
    secs: 7,
    vo: 'On one sparse layer of GLM, it has two hundred and eighty-eight routed experts to choose from.',
    commands: [
      camera.to({ x: 50, y: 48 }, 0.86),
      hospital.show({ x: 52, y: 44 }, 0.9, { staffed: true }),
      desk.moveTo({ x: 62, y: 74 }, 0.66),
      row.moveTo({ x: 30, y: 78 }, 0.4),
      narrator.set({ pose: 'reach' }),
    ],
    lateOverlays: {
      at: 2600,
      overlays: [note('288 routed experts', 82, 22, { size: 'md', tone: 'measure', rotate: 2, sticky: true })],
    },
  },
  {
    n: 4,
    id: 'exactly-one-thing',
    title: 'The row arrives at the desk and stops; the whole wall waits, unscored',
    relation: 'so',
    secs: 5,
    vo: 'The row comes in.',
    commands: [row.moveTo({ x: 40, y: 78 }, 0.4), hospital.plain(), narrator.set({ pose: 'wonder' })],
  },
  {
    n: 5,
    id: 'every-single-one',
    title: 'An empty score badge appears on all 288 at once',
    relation: 'so',
    secs: 7,
    vo: 'And the router scores all two hundred and eighty-eight experts.',
    commands: [hospital.ask(), narrator.set({ pose: 'count' })],
  },
  {
    n: 6,
    id: 'how-well-do-you-fit',
    title: 'A sweep crosses the whole wall left to right, filling every badge',
    relation: 'so',
    secs: 10,
    vo: 'Each score is basically asking: how well does this expert fit the row I have right now?',
    commands: [hospital.score(), row.pulse()],
    lateOverlays: {
      at: 3200,
      overlays: [note('score all 288', 16, 22, { tone: 'measure', rotate: -3 })],
    },
  },
  {
    n: 7,
    id: 'these-numbers-right-now',
    title: 'The badges settle; the row stays lit beside them',
    relation: 'and-yet',
    secs: 11,
    vo: 'And "right now" matters. It is not scoring the word "dog". It is scoring this current representation, after context changed it.',
    commands: [row.pulse(), narrator.set({ pose: 'point' })],
    overlays: [note('current row —\nnot the raw word', 16, 82, { size: 'md', tone: 'word', rotate: -2 })],
  },
  {
    n: 8,
    id: 'keeps-the-best-eight',
    title: 'The eight highest rise forward; the other 280 go flat',
    relation: 'therefore',
    secs: 6,
    vo: 'Then it keeps the top eight.',
    commands: [hospital.choose(CHOSEN)],
  },
  {
    n: 9,
    id: 'eight-of-two-eighty-eight',
    title: 'A bracket draws around the eight and counts them against the wall',
    relation: 'and-yet',
    secs: 10,
    vo: 'Eight routed experts run. The other two hundred and eighty routed experts on this layer sit idle.',
    commands: [
      count.show({ x: 15, y: 40 }, 1, { value: 8, label: 'of 288 did anything' }),
      hospital.idle('280 idle'),
    ],
  },
  {
    n: 10,
    id: 'no-dog-expert',
    title: 'Name-plates try to land on the eight and slide off',
    relation: 'wall',
    secs: 15,
    vo: 'And these are not clean human-readable specialists like a "dog expert" or a "math expert". We do not know neat semantic jobs for them.',
    commands: [plates.land()],
    stages: [{ at: 6000, commands: [plates.slideOff(), narrator.set({ pose: 'flat' })] }],
    lateOverlays: {
      at: 7000,
      overlays: [note('no semantic name-plate', 80, 76, { size: 'md', tone: 'cost', rotate: 3 })],
    },
  },
  {
    n: 11,
    id: 'what-an-expert-is',
    title: 'One expert lifts out and opens: a row in, a different row out',
    relation: 'so',
    secs: 11,
    vo: 'An expert is just a learned feed-forward block: a row goes in, and a transformed row comes out.',
    commands: [plates.off(), open.show({ x: 50, y: 48 }, 1.05)],
  },
  {
    n: 12,
    id: 'one-more-over-here',
    title: 'A ninth slides in from outside the wall entirely, already lit',
    relation: 'so',
    secs: 13,
    vo: 'GLM also has one shared expert, separate from those two hundred and eighty-eight. It is not scored or selected. It runs every time.',
    commands: [open.off(), shared.show({ x: 86, y: 30 }, 1.6)],
    lateOverlays: {
      at: 4200,
      overlays: [note('+1 shared expert\nalways runs', 84, 54, { tone: 'relate', rotate: 3, sticky: true })],
    },
  },
  {
    n: 13,
    id: 'look-what-the-scores-came-from',
    title: 'The row that produced the scores pulses; a line links it to the badges',
    relation: 'wall',
    secs: 7,
    vo: 'Now look back at what the router used to make those scores: this row.',
    commands: [row.moveTo({ x: 15, y: 62 }, 0.4), row.pulse(), narrator.set({ pose: 'point' })],
    clearSticky: true,
  },
  {
    n: 14,
    id: 'only-just-finished-making-them',
    title: 'Attention’s arcs ghost in behind the row, then fade',
    relation: 'and-yet',
    secs: 8,
    vo: 'That row only existed after the context step finished.',
    commands: [arcs.show({ x: 15, y: 54 }, 0.6)],
    stages: [{ at: 4600, commands: [arcs.off()] }],
  },
  {
    n: 15,
    id: 'change-the-sentence',
    title: 'A second sentence swaps in; the row changes; most of the eight change',
    relation: 'therefore',
    secs: 14,
    vo: 'Change the sentence and the row changes. Change the row and the scores change. And the selected eight can change too.',
    commands: [row2.show({ x: 15, y: 66 }, 0.34), hospital.remember(CHOSEN)],
    stages: [{ at: 4000, commands: [hospital.choose(OTHER)] }],
  },
  {
    n: 16,
    id: 'could-not-have-been-earlier',
    title: 'The new eight hold; the old eight’s empty places stay marked',
    relation: 'and-yet',
    secs: 14,
    vo: 'So the router could not have picked its experts before seeing the current row. The active part is not one fixed chunk sitting somewhere waiting for every token.',
    commands: [narrator.set({ pose: 'think' })],
    lateOverlays: {
      at: 3600,
      overlays: [note('the choice depends on\nthe current row', 78, 78, { size: 'md', tone: 'cost', rotate: -2 })],
    },
  },
]
