import { centred, GROUND_Y, note, tick, type Beat } from '../../../../paper'
import {
  GB_PER_TOKEN,
  MB_PER_EXPERT,
  VISITS,
  bars,
  camera,
  clock,
  count,
  desk,
  ground,
  machine,
  narrator,
  shelf,
  numbers,
  path,
  store,
  total,
  tower,
  type Patch,
} from './scene'

/**
 * Section 11 — Why not keep only the active part?
 *
 * This section does NOT claim the full model must live in GPU memory. It tests
 * one simple plan: leave routed experts on slower storage and fetch each
 * selected expert just in time. The arithmetic is intentionally a worst-case
 * "nothing useful is already resident" illustration; §12 then shows the real
 * improvement: cache/offload systems keep useful experts nearby.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'back-to-where-we-started',
    title: '`18` and `320` return and settle over the tower',
    relation: 'want',
    secs: 11,
    vo: 'Now we can ask it properly. If each token only uses a small subset, why not keep only that subset in fast memory?',
    commands: [
      ground.at(GROUND_Y),
      tower.show({ x: 26, y: 48 }, 0.82),
      numbers.show({ x: 68, y: 36 }, 1),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'point', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'heres-the-plan',
    title: 'We slide across to the plan, assembling itself piece by piece',
    relation: 'so',
    secs: 15,
    vo: 'Try the simplest version. Keep the full checkpoint on slower storage. When a sparse layer picks eight experts, fetch those eight into fast memory, run them, then move on.',
    commands: [
      tower.off(),
      numbers.off(),
      camera.to({ x: 50, y: 50 }, 1),
      store.show({ x: 15, y: 42 }, 0.7),
      ground.at(GROUND_Y),
    ],
    stages: [
      { at: 1400, commands: [desk.show({ x: 45, y: 70 }, 0.46)] },
      { at: 2800, commands: [machine.show({ x: 82, y: 42 }, 0.72)] },
    ],
  },
  {
    n: 3,
    id: 'it-works',
    title: 'Eight blocks fly across; the work completes; a tick lands',
    relation: 'hope',
    secs: 8,
    vo: 'For one sparse layer, that works. Fetch eight, run them.',
    commands: [path.fetch(8), machine.set({ filled: true }), narrator.set({ pose: 'hopeful' })],
    lateOverlays: {
      at: 2800,
      overlays: [tick(82, 22, { tone: 'measure' }), note('one layer — fine', 82, 30, { rotate: -3 })],
    },
  },
  {
    n: 4,
    id: 'second-floor',
    title: 'Eight *different* blocks fly across',
    relation: 'so',
    secs: 7,
    vo: 'Next sparse layer: the row changed, so you may need a different eight.',
    commands: [path.fetch(8)],
    overlays: [centred('next layer — another selection', 50, 24, { tone: 'measure', rotate: 2 })],
  },
  {
    n: 5,
    id: 'third-floor',
    title: 'Eight more',
    relation: 'so',
    secs: 4,
    vo: 'Then the next one.',
    commands: [path.fetch(10)],
  },
  {
    n: 6,
    id: 'forty-two-times',
    title: 'The flights speed up until the path is continuously full',
    relation: 'wall',
    secs: 8,
    vo: 'Across forty-two sparse layers, the naive version keeps doing this over and over.',
    commands: [path.congest(), narrator.set({ pose: 'slump' })],
  },
  {
    n: 7,
    id: 'how-much-did-we-carry',
    title: 'The flights stop; a counter lands',
    relation: 'so',
    secs: 8,
    vo: 'So how much data moves for one token if none of those routed experts are already nearby?',
    commands: [path.clear(), count.run(VISITS, 'expert visits — one token')],
  },
  {
    n: 8,
    id: 'three-thirty-six-times-twenty-six',
    title: '336 and 25 MB slide together; a total assembles',
    relation: 'so',
    secs: 13,
    vo: 'One routed expert here is about twenty-five megabytes in FP8. Three hundred and thirty-six expert visits times twenty-five megabytes is about eight and a half gigabytes of routed weights.',
    commands: [count.hold()],
    overlays: [
      centred(`${VISITS} × ${MB_PER_EXPERT} MB`, 50, 60, { size: 'lg', tone: 'measure', rotate: -2, sticky: true }),
    ],
  },
  {
    n: 9,
    id: 'for-one-word',
    title: 'The total lands and a label drops under it',
    relation: 'and-yet',
    secs: 9,
    vo: 'For one token, in the worst-case version where none of those routed weights were already resident.',
    commands: [
      count.off(),
      store.off(),
      desk.off(),
      total.show({ x: 40, y: 40 }, 1.2),
      narrator.set({ pose: 'shrug' }),
    ],
    clearSticky: true,
  },
  {
    n: 10,
    id: 'a-second-and-a-half',
    title: 'A clock draws itself beside the 8 GB and runs',
    relation: 'wall',
    secs: 11,
    vo: 'At five gigabytes a second, moving eight and a half gigabytes takes about one point seven seconds.',
    commands: [machine.off(), clock.show({ x: 74, y: 40 }, 1), clock.start()],
    overlays: [note('5 GB/s → ~1.7 s', 74, 62, { tone: 'cost', rotate: 3 })],
  },
  {
    n: 11,
    id: 'and-the-work',
    title: 'A second bar appears beside the first, almost invisible',
    relation: 'and-yet',
    secs: 9,
    vo: 'The expert computation we were trying to feed is millisecond-scale by comparison.',
    commands: [
      total.off(),
      clock.off(),
      path.off(),
      bars.fetch(),
      bars.both('roughly 50× in this comparison'),
      narrator.set({ pose: 'weigh' }),
    ],
  },
  {
    n: 12,
    id: 'fetching-costs-more',
    title: 'Both bars redraw to true scale, with the small one magnified',
    relation: 'therefore',
    secs: 12,
    vo: 'So this naive plan is dominated by data movement. In this rough comparison, fetching can cost around fifty times more time than the expert compute.',
    commands: [bars.toScale()],
    lateOverlays: {
      at: 3200,
      overlays: [centred('the transfer dominates\nthis naive plan', 50, 18, { size: 'md', tone: 'cost', rotate: -1 })],
    },
  },
  {
    n: 13,
    id: 'not-like-that',
    title: 'The bars hold; nothing else on screen',
    relation: 'therefore',
    secs: 12,
    vo: 'So “store everything slow and fetch every selected expert just in time” is not a good serving strategy. Not like this.',
    commands: [narrator.set({ pose: 'halt' })],
    overlays: [centred(`~${GB_PER_TOKEN} GB per token — worst-case routed fetch`, 50, 88, { size: 'md', rotate: 1 })],
  },
  {
    n: 14,
    id: 'just-keep-the-popular-ones',
    title: 'A small cache shelf sketches itself in beside the bars',
    relation: 'and-yet',
    secs: 8,
    vo: 'But there is an obvious improvement. What if some experts come back?',
    commands: [shelf.show({ x: 24, y: 80 }, 0.58, { outline: true }), narrator.set({ pose: 'confide' })],
  },
  {
    n: 15,
    id: 'hold-that-thought',
    title: 'The shelf finishes drawing and stays, empty',
    relation: 'and-yet',
    secs: 11,
    vo: 'Keep useful experts in fast memory, and only fetch the misses. Exactly. That is caching — and it is how real expert offloading becomes practical.',
    commands: [shelf.finish(), narrator.set({ pose: 'nod' })],
    clearSticky: true,
    lateOverlays: {
      at: 3000,
      overlays: [centred('keep hits nearby · fetch misses', 48, 88, { size: 'md', tone: 'word', rotate: -2 })],
    },
  },
]
