import { brace, GROUND_Y, note, type Beat } from '../../../../paper'
import {
  again1,
  again2,
  camera,
  cat,
  chip,
  dog,
  ground,
  narrator,
  space,
  table,
  tues,
  type Patch,
} from './scene'

/**
 * Section 03 — From an ID to a meaning.
 *
 * The viewer already owns the problem: a token ID is an address, not a
 * meaning. This section simply uses the address, watches the lookup happen,
 * then shows why a long row of numbers is useful before naming it.
 */
export const BEATS: Beat<Patch>[] = [
  {
    n: 1,
    id: 'how-it-gets-meaning',
    title: '`5562` alone; a table edge rises into frame',
    relation: 'want',
    secs: 10,
    vo: 'Exactly. Five thousand, five hundred and sixty-two is an address, not a meaning. So let’s use the address.',
    commands: [
      ground.at(GROUND_Y),
      chip.show({ x: 46, y: 46 }, 1, { becomes: true }),
      table.show({ x: 22, y: 118 }, 1),
      narrator.show({ x: 91, y: 70 }, 1, { pose: 'point', flip: true }),
    ],
  },
  {
    n: 2,
    id: 'the-model-has-a-table',
    title: 'We back away; the table runs past the top of frame',
    relation: 'so',
    secs: 11,
    vo: 'The model has another huge table: one row for every token it knows. All one hundred and fifty-four thousand, eight hundred and eighty.',
    commands: [
      table.moveTo({ x: 24, y: 50 }, 1),
      camera.to({ x: 46, y: 46 }, 0.92),
      chip.moveTo({ x: 62, y: 30 }, 0.8),
      narrator.set({ pose: 'reach' }),
    ],
    lateOverlays: {
      at: 3000,
      overlays: [note('one row per token\n154,880 rows', 8, 84, { tone: 'measure', rotate: -3, sticky: true })],
    },
  },
  {
    n: 3,
    id: 'which-row-to-fetch',
    title: 'The number travels up the table to its own row',
    relation: 'so',
    secs: 5,
    vo: 'The ID tells us which row to fetch.',
    commands: [table.seek(), chip.moveTo({ x: 34, y: 46 }, 0.6)],
  },
  {
    n: 4,
    id: 'this-row',
    title: 'That row slides out of the table and comes forward',
    relation: 'so',
    secs: 5,
    vo: 'So we pull out row five thousand, five hundred and sixty-two.',
    commands: [table.pull(), chip.off(), dog.show({ x: 66, y: 40 }, 0.62, { label: '' })],
  },
  {
    n: 5,
    id: 'four-thousand-and-ninety-six',
    title: 'The row extends sideways past both edges of frame',
    relation: 'and-yet',
    secs: 8,
    vo: 'And that one row contains four thousand and ninety-six numbers. For one token.',
    commands: [table.moveTo({ x: 6, y: 50 }, 1), dog.set({ extend: true }), dog.moveTo({ x: 54, y: 40 }, 0.8)],
    clearSticky: true,
    overlays: [
      brace('4,096 numbers — for one token', 26, 62, 56, { tone: 'measure', voice: 'figure', sticky: true }),
    ],
  },
  {
    n: 6,
    id: 'what-for',
    title: 'Everything stops; the row holds and the question sits under it',
    relation: 'and-yet',
    secs: 9,
    vo: 'That sounds ridiculous. Why would a token like "dog" need four thousand numbers?',
    commands: [dog.set({ extend: false }), dog.moveTo({ x: 64, y: 32 }, 0.58), narrator.set({ pose: 'wonder' })],
    clearSticky: true,
    lateOverlays: {
      at: 2400,
      overlays: [note('what are they for?', 56, 62, { size: 'lg', rotate: -2, sticky: true })],
    },
  },
  {
    n: 7,
    id: 'dog-and-cat',
    title: 'Two more rows slide out and stack under it',
    relation: 'so',
    secs: 8,
    vo: 'Because one number cannot capture much about a word. Compare "dog" with "cat".',
    commands: [
      dog.set({ label: 'dog' }),
      cat.show({ x: 64, y: 48 }, 0.58, { label: 'cat' }),
      narrator.set({ pose: 'point' }),
    ],
    clearSticky: true,
  },
  {
    n: 8,
    id: 'close-but-not-the-same',
    title: 'The two rows align and light as one band',
    relation: 'so',
    secs: 8,
    vo: 'Their rows are not identical. But taken as whole patterns, they can sit relatively close to each other.',
    commands: [
      dog.compare(),
      cat.compare(),
      dog.moveTo({ x: 62, y: 36 }, 0.58),
      cat.moveTo({ x: 62, y: 50 }, 0.58),
    ],
    overlays: [note('close — as\nwhole rows', 82, 42, { size: 'md', tone: 'word', rotate: -4 })],
  },
  {
    n: 9,
    id: 'now-tuesday',
    title: 'A third row aligns; its band stays unlit',
    relation: 'wall',
    secs: 6,
    vo: 'Now compare either of them with "Tuesday". Much farther away.',
    commands: [tues.show({ x: 62, y: 66 }, 0.58, { label: 'Tuesday' }), tues.compare()],
    overlays: [note('farther away', 82, 68, { size: 'md', tone: 'cost', rotate: 3 })],
  },
  {
    n: 10,
    id: 'training-did-it',
    title: 'The three rows fold into three points, spaced by likeness',
    relation: 'so',
    secs: 12,
    vo: 'Nobody hand-placed them there. Training shaped the table so tokens used in similar situations tend to end up in similar regions.',
    commands: [dog.off(), cat.off(), tues.off(), space.fold()],
    lateOverlays: {
      at: 3000,
      overlays: [note('illustration only —\nrelative distance', 82, 78, { rotate: 3 })],
    },
  },
  {
    n: 11,
    id: 'where-the-row-sits',
    title: 'The points hold; a brace measures the two distances',
    relation: 'and-yet',
    secs: 11,
    vo: 'So the useful information is not one magic coordinate. It is the pattern of the whole row, and how that pattern relates to other rows.',
    commands: [space.measure(), narrator.set({ pose: 'aha' })],
  },
  {
    n: 12,
    id: 'called-an-embedding',
    title: 'The points unfold back into the `dog` row; a label lands on it',
    relation: 'therefore',
    secs: 9,
    vo: 'That row of numbers is called an embedding. It is the model’s starting representation for this token.',
    commands: [space.unfold(), dog.show({ x: 60, y: 40 }, 0.72, { matches: false, label: 'dog' }), narrator.set({ pose: 'nod' })],
    lateOverlays: {
      at: 2600,
      overlays: [note('embedding', 54, 20, { size: 'lg', tone: 'measure', rotate: -2, sticky: true })],
    },
  },
  {
    n: 13,
    id: 'this-is-what-goes-in',
    title: 'The label settles; the row sits alone in frame',
    relation: 'therefore',
    secs: 9,
    vo: 'So when our token enters the model, this four-thousand-and-ninety-six-number embedding is what it starts with.',
    commands: [dog.moveTo({ x: 60, y: 44 }, 0.72), narrator.set({ pose: 'nod' })],
    clearSticky: true,
  },
  {
    n: 14,
    id: 'stored-in-a-table',
    title: 'The same row is pulled from the table a second time, beside the first',
    relation: 'and-yet',
    secs: 6,
    vo: 'But remember: it came from a lookup table.',
    commands: [
      table.moveTo({ x: 24, y: 50 }, 1),
      dog.moveTo({ x: 60, y: 34 }, 0.62),
      again1.show({ x: 60, y: 52 }, 0.62),
      narrator.set({ pose: 'think' }),
    ],
  },
  {
    n: 15,
    id: 'same-word-same-row',
    title: 'Pulled a third time; all three sit identical',
    relation: 'wall',
    secs: 13,
    vo: 'So the same token starts with the same embedding every time. "Dog" here, "dog" somewhere else — same starting row. How can its meaning ever change?',
    commands: [again2.show({ x: 60, y: 70 }, 0.62)],
    lateOverlays: {
      at: 3000,
      overlays: [note('same starting row.\nevery time.', 82, 34, { size: 'md', tone: 'cost', rotate: -3 })],
    },
  },
]
