/**
 * Generates storyboard/BOARD.md from the beats themselves.
 *
 * A hand-written board drifts from the code within a day, and then two
 * documents disagree about what the video is. This one cannot: it is read out
 * of every section's beats.ts, so the board and the build are the same fact.
 *
 * Run: node scripts/board.mjs   (or npm run board)
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = 'src/videos/glm-320b'
const SCRIPTS = {
  '01': ['01-the-claim.md', 'The claim on trial'],
  '02': ['02-follow-one-word.md', 'Follow one word in'],
  '03': ['03-the-word-becomes-numbers.md', 'The word becomes numbers'],
  '04': ['04-where-the-numbers-change.md', 'Where the numbers change'],
  '05': ['05-new-numbers-new-team.md', 'New numbers, new team'],
  '06': ['06-forty-two-floors.md', 'Forty-two floors'],
  '07': ['07-the-answer.md', 'The answer'],
  '08': ['08-the-verdict.md', 'The verdict'],
}

/** beats.ts imports story verbs, so it cannot be evaluated standalone. */
function parseBeats(source) {
  const beats = []
  for (const block of source.split(/\n {2}\{\n/).slice(1)) {
    const n = block.match(/^ {4}n: (\d+),/)
    if (!n) continue
    const pick = (key) => {
      const hit = block.match(new RegExp(`\\n {4}${key}: (['"\`])([\\s\\S]*?)\\1,\\n`))
      return hit ? hit[2] : ''
    }
    beats.push({
      n: Number(n[1]),
      id: pick('id'),
      title: pick('title'),
      relation: pick('relation'),
      vo: pick('vo').replace(/\\u2014/g, '—').replace(/\s+/g, ' ').trim(),
      secs: Number((block.match(/\n {4}secs: ([0-9.]+),/) ?? [0, 0])[1]),
      event: / EVENT| THE PAYOFF|THE CONTRADICTION/.test(block),
      frozen: /FROZEN FRAME/.test(block),
    })
  }
  return beats
}

function field(source, name) {
  const row = source.match(new RegExp(`^\\|\\s*\\*{0,2}${name}\\*{0,2}\\s*\\|(.+?)\\|\\s*$`, 'mi'))
  return row ? row[1].replace(/\*+/g, '').trim() : ''
}

const dirs = (await readdir(ROOT, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && /^section-\d\d$/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const out = []
const A = (line = '') => out.push(line)

A('# Storyboard — every beat, every section')
A('')
A('**Generated by `npm run board`. Do not edit by hand.**')
A('')
A('A hand-written board drifts from the code within a day, and then two')
A('documents disagree about what the video is. This one is read out of each')
A("section's `beats.ts`, so the board and the build are the same fact.")
A('')
A('Spine: `storyboard/STORY_SPINE.md` · Gates: `skills/STORY_STRUCTURE.md`')
A('Chain check: `npm run check:chain` · Frames: `npm run frames:all`')
A('')

let grand = 0
const summary = []

for (const dir of dirs) {
  const key = dir.slice(-2)
  const [scriptFile, title] = SCRIPTS[key] ?? [null, dir]
  const beats = parseBeats(await readFile(path.join(ROOT, dir, 'beats.ts'), 'utf8'))
  const total = beats.reduce((sum, beat) => sum + beat.secs, 0)
  grand += total

  let enters = ''
  let exits = ''
  let event = ''
  if (scriptFile) {
    const script = await readFile(path.join('video-script', scriptFile), 'utf8')
    enters = field(script, 'Enters on')
    exits = field(script, 'Exits on')
    event = field(script, 'Event')
  }

  summary.push({ key, title, beats: beats.length, total, exits })

  A(`## Section ${key} — ${title}`)
  A('')
  A(`\`${beats.length}\` beats · \`${Math.floor(total / 60)}:${String(Math.round(total % 60)).padStart(2, '0')}\` · script: \`video-script/${scriptFile ?? '—'}\` · route: \`/${dir}\``)
  A('')
  if (enters) A(`- **Enters on** — ${enters}`)
  if (event) A(`- **Event** — ${event}`)
  if (exits) A(`- **Exits on** — ${exits}`)
  A('')
  A('| # | id | s | rel | Beat | Voice |')
  A('| --- | --- | --- | --- | --- | --- |')
  for (const beat of beats) {
    const mark = beat.event ? ' ⚑' : beat.frozen ? ' ❄' : ''
    A(`| ${beat.n} | \`${beat.id}\` | ${beat.secs} | ${beat.relation} | ${beat.title}${mark} | ${beat.vo || '—'} |`)
  }
  A('')
}

A('---')
A('')
A('## Totals')
A('')
A('| § | Section | Beats | Runtime | Hands forward |')
A('| --- | --- | --- | --- | --- |')
for (const row of summary) {
  A(
    `| ${row.key} | ${row.title} | ${row.beats} | ${Math.floor(row.total / 60)}:${String(
      Math.round(row.total % 60),
    ).padStart(2, '0')} | ${row.exits || '—'} |`,
  )
}
const beatCount = summary.reduce((sum, row) => sum + row.beats, 0)
A(
  `| | **whole piece** | **${beatCount}** | **${Math.floor(grand / 60)}:${String(
    Math.round(grand % 60),
  ).padStart(2, '0')}** | |`,
)
A('')
A('⚑ the section\'s event · ❄ a frame that must read as a still')
A('')

await writeFile('storyboard/BOARD.md', `${out.join('\n')}\n`, 'utf8')
console.log(`storyboard/BOARD.md — ${dirs.length} sections, ${beatCount} beats, ${Math.floor(grand / 60)}:${String(Math.round(grand % 60)).padStart(2, '0')}`)
