/**
 * Sound effects, fired by the beat that causes them.
 *
 * ## Why this is not placed in an editor
 *
 * The alternative is a cue sheet of timecodes dropped onto a timeline by hand.
 * That works exactly once: the moment any `secs` changes -- and every one of
 * them will change when the real voice is recorded -- every cue after it is
 * wrong, silently, and re-placing forty-one of them is an afternoon.
 *
 * Anchoring to **beat ids** instead means the cue cannot drift. The beat fires,
 * the sound fires. Restamping the whole video moves nothing.
 *
 * The same `output/sfx/cues.json` also builds the offline track
 * (`scripts/sfx-track.mjs`), so what you hear while scrubbing is exactly what
 * ends up in the render. One source, two consumers, no hand-placement.
 *
 * Cues are fetched, not imported: they are generated by `npm run sfx:cues` and
 * a missing file is silence, never a broken page.
 */

export type Cue = {
  section: number
  beat: string
  sound: string
  /** Seconds from the start of the beat. */
  offset: number
  gainDb: number
  kind?: string
}

/**
 * Automation never plays sound.
 *
 * Playwright captures no audio, and the rendered track is built offline from
 * the same cues (`scripts/sfx-track.mjs`) -- so playing it during a capture
 * buys nothing and costs a real bug: `npm run smoke` walks 33 routes, navigates
 * away mid-fetch, and every aborted media request counts as a failed one. The
 * seam cue on beat 1 of every section failed exactly this way.
 *
 * Silencing the gate would have been the wrong fix. Not making the request is
 * the right one.
 */
const AUTOMATED = typeof navigator !== 'undefined' && navigator.webdriver === true

let loaded: Promise<Map<string, Cue[]>> | null = null
const buffers = new Map<string, HTMLAudioElement>()

const key = (section: number, beat: string) => `${section}/${beat}`

/** One fetch for the whole session, and silence if it is not there. */
function cues(): Promise<Map<string, Cue[]>> {
  if (loaded) return loaded
  loaded = fetch('/sfx/cues.json')
    .then((r) => (r.ok ? r.json() : []))
    .then((list: Cue[]) => {
      const map = new Map<string, Cue[]>()
      for (const c of list) {
        const k = key(c.section, c.beat)
        map.set(k, [...(map.get(k) ?? []), c])
      }
      return map
    })
    .catch(() => new Map())
  return loaded
}

const gain = (db: number) => Math.min(1, Math.max(0, 10 ** (db / 20)))

/**
 * Lazily, and only for sounds a beat actually uses.
 *
 * This used to preload all thirteen on every page. `npm run smoke` caught it:
 * it walks 33 routes quickly, the in-flight preloads abort on navigation, and
 * every section logged failed requests. A section needs two or three sounds --
 * fetching thirteen was both wrong and wasteful.
 */
function master(sound: string): HTMLAudioElement {
  let el = buffers.get(sound)
  if (!el) {
    el = new Audio(`/sfx/${sound}`)
    el.preload = 'auto'
    buffers.set(sound, el)
  }
  return el
}

function play(cue: Cue) {
  const master_ = master(cue.sound)
  if (!master_) return
  /*
   * A clone per hit. One element cannot overlap itself, and §3 beat 15 fires
   * the same click three times inside a second -- on a shared element the
   * second call restarts the first and you hear one.
   */
  const el = master_.cloneNode() as HTMLAudioElement
  el.volume = gain(cue.gainDb ?? -8)
  void el.play().catch(() => {})
}

/**
 * Schedules one beat's cues. Returns a cancel function.
 *
 * `from` is how far into the beat we already are, so a cue whose moment has
 * passed is skipped rather than fired late -- which is what happens when a
 * viewer scrubs backwards into the middle of a beat.
 */
export function fireBeat(section: number, beat: string, from = 0): () => void {
  if (AUTOMATED) return () => {}
  const timers: number[] = []
  let cancelled = false
  void cues().then((map) => {
    if (cancelled) return
    for (const cue of map.get(key(section, beat)) ?? []) {
      master(cue.sound) // warm this one, and only this one
      const wait = (cue.offset - from) * 1000
      if (wait < -250) continue
      timers.push(window.setTimeout(() => play(cue), Math.max(0, wait)))
    }
  })
  return () => {
    cancelled = true
    for (const t of timers) window.clearTimeout(t)
  }
}
